version: 0.1.{build}-{branch}
pull_requests:
  do_not_increment_build_number: true

image:
  - Ubuntu
  - Visual Studio 2017

# loguru is header-only
build: off

test_script: cmake -P test/appveyor.cmake
